- name: Execute a script on all instances
  hosts: all
  gather_facts: yes

  tasks:
  - name: Copy script to instance
    copy:
      src: script.sh
      dest: /tmp/script.sh
      mode: '0755'

  - name: Execute the script
    become: yes
    command: bash /tmp/script.sh

  - name: Remove the script
    become: yes
    command: sudo rm -f /tmp/script.sh
